CREATE TABLE jobs (
  id VARCHAR PRIMARY KEY,
  status VARCHAR NOT NULL,
  title VARCHAR NOT NULL,
  company VARCHAR NOT NULL,
  url VARCHAR NOT NULL,
  location VARCHAR NOT NULL,
  date_submitted TIMESTAMP NOT NULL,
  note VARCHAR,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
)
