# Generated by Django 4.0 on 2022-01-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='user_jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auth.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
