# Generated by Django 4.0 on 2022-01-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_user_alter_jobs_user_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_cache_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
            ],
        ),
    ]
