# Generated by Django 4.0 on 2022-01-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0004_my_cache_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my_cache_table',
        ),
    ]
